### ISSUE TITLE
Implement instruction page for sending the e-mails

### ISSUE THREAD

**Issue by leonbotros** [privacybydesign/irma-welkom#18]
Does the host send this email or Procolix? Bcc link, etc?

**Comment by bvgastel** [comment]
Proposal: keep it simple for initial version, and let Procolix send all the mails. Based on actual user feedback we can revisit this decision. Ok?

**Comment by bwesterb** [comment]
Maar dan kun je alle IBE er gewoon uitgooien en alles in een database bij Procolix zetten.

Ik neem aan dat het probleem van een mailto: link is dat niet iedereen hun mailclient geconfigureerd heeft op hun telefoon?

**Comment by leonbotros** [comment]
Het idee is wel dat de emails die gemaild moeten worden van de host naar de backend bij procolix gaan nadat iemand corona gemeld heeft aan de host. Dit zou een kleine subset moeten zijn en ook heeft de host dan geen inzeg in wat hij mailt (reclame bijv).
Ik vind het alsnog niet ideaal nee, Bas.

**Comment by bvgastel** [comment]
Meeting: keep it simple, display a link with `mailto:` AND show a comma separated list as fallback (if no mail client is shown, possibly as a copy-to-clipboard button), with some explanation that they should be pasted in BCC.

**Comment by bvgastel** [comment]
First step is to make the texts / design.
