### ISSUE TITLE
[Front-end] Responsive / Fix mobile view 

### ISSUE THREAD

**Issue by CreativeCode** [privacybydesign/irma-welkom#19]
The front-end shows the desktop site on mobile screens such as on the iPhone X.

Current behavior is shown in screenshot:
![IMG_6052](https://user-images.githubusercontent.com/11244145/97289302-4c7df580-1847-11eb-83f9-93e32e339dc8.PNG)

Intended look:

![image](https://user-images.githubusercontent.com/11244145/97289423-720aff00-1847-11eb-8624-c6360292d5f8.png)

**Comment by leonbotros** [comment]
@CreativeCode , how did you get this intended look to show up?

**Comment by CreativeCode** [comment]
I did this by resizing the site in chrome. Maybe fix it by adding this inside <head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
**
